# Generated by Django 5.0.1 on 2024-01-10 12:08

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره همراه')),
                ('department', models.CharField(max_length=30, verbose_name='نام دپارتمان')),
                ('user_token', models.CharField(max_length=30, verbose_name='توکن دسترسی')),
                ('join_date', django_jalali.db.models.jDateTimeField()),
            ],
        ),
    ]
