# Generated by Django 5.0.1 on 2024-01-10 12:18

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seassons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فصل')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', django_jalali.db.models.jDateTimeField()),
                ('first_team_result', models.IntegerField(default=0)),
                ('second_team_result', models.IntegerField(default=0)),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_B', to='main.teams')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='main.teams')),
            ],
        ),
    ]
