# Generated by Django 5.0.1 on 2024-01-10 12:31

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seassons_teams_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان شروع'),
        ),
        migrations.AlterField(
            model_name='games',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='تیم اول'),
        ),
        migrations.AlterField(
            model_name='games',
            name='first_team_result',
            field=models.IntegerField(default=0, verbose_name='نتیجه تیم اول'),
        ),
        migrations.AlterField(
            model_name='games',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_B', to='main.teams', verbose_name='تیم دوم'),
        ),
        migrations.AlterField(
            model_name='games',
            name='second_team_result',
            field=models.IntegerField(default=0, verbose_name='نتیجه تیم دوم'),
        ),
        migrations.AlterField(
            model_name='games',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='main.teams', verbose_name='برنده بازی'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان تیم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ثبت نام'),
        ),
    ]
