# Generated by Django 5.0.1 on 2024-01-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_games_date_time_alter_games_first_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='seasson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.seassons', verbose_name='انتخاب فصل'),
        ),
    ]
