# Generated by Django 5.0.1 on 2024-01-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='first_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userform',
            name='second_team',
            field=models.IntegerField(default=0),
        ),
    ]
