# Generated by Django 5.0.1 on 2024-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userform_first_team_userform_second_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
