# Generated by Django 4.2.2 on 2024-01-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_games_first_team_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='first_team',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='second_team',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
