# Generated by Django 5.0.1 on 2024-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_winnerresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
